### PR TITLE
Add non-x86 support

### PR DESCRIPTION
**Pull request by jameshloving**

### CODE REVIEW

**Comment by armon** [comment]
@jameshloving It looks like this is failing the Travis tests with a compile error. Could you please resolve that for the PR?

**Comment by jameshloving** [comment]
Hi Armon,

Looking more into the error, it doesn't seem to be anything on my end:
https://travis-ci.org/armon/bloomd/builds/184398925 shows an error with pip
install, not the actual compilation. Please let me know if I'm wrong.

Thanks and happy New Year!

James Loving
jloving@mit.edu | jameshloving@gmail.com

**Comment by armon** [comment]
@jameshloving Happy New Years to you as well! I fixed the pip issue with bloomd, but it looks like there is a double definition of `cmp` : https://travis-ci.org/armon/libart/jobs/184411772

**Comment by jameshloving** [comment]
Should be fixed!

**Comment by armon** [comment]
Thanks!

**Pull request merged**
