### PR TITLE
compile a shared object, make test_runner depend on it, allow in tree…

### PR DESCRIPTION
**Pull request by rileyberton**
… check depends

Heyya, Armon.

We are going to use libart for a new project here at Circonus but we have some build tweaks to auto-create a shared object and to be able to use check in-tree.

Let me know what you think about merging this or if you think there should be another approach.

Thanks,

### CODE REVIEW

**Comment by armon** [comment]
@rileyberton It seems to be failing the Travis checks. Anything we need to change to make that pass? If that is passing, I'd be happy to merge it!

**Comment by rileyberton** [comment]
I believe this is an LD_LIBRARY_PATH problem.  The Travis job does this:

`$ CK_TIMEOUT_MULTIPLIER=3 ./test_runner`

Which fails with:

./test_runner: error while loading shared libraries: libart.so: cannot open shared object file: No such file or directory

I think if we change the test_runner invocation to:

`$ CK_TIMEOUT_MULTIPLIER=3 LD_LIBRARY_PATH=`pwd` ./test_runner`

It will pass.

**Comment by rileyberton** [comment]
I fixed the Travis job.  Apologies for the oversight.

**Comment by armon** [comment]
Thanks!

**Pull request merged**
